on:
- workflow_dispatch
- push
name: Publish PowerShell Module

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v2
    - id: publish-module
      name: Publish Module
      shell: pwsh
      run: |
        mkdir kubetools
        Move-Item -Path kubetools.psd1,kubetools.psm1 -Destination kubetools
        Get-ChildItem
        Publish-Module -Path ./kubetools/ -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_APIKEY }}
