on:
- workflow_dispatch
- push
name: Publish PowerShell Module

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - id: publish-module
      name: Publish Module
      shell: pwsh
      run: |
        $ExcludeList = @('README.md', 'publish.yml')
        Import-Module -Name ${{ github.workspace}}/kubetools.psd1
        Publish-Module -Name kubetools -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_APIKEY }} -Exclude $ExcludeList
